server:
  port: ${PORT:8081}

spring:
  zipkin:
    discovery-client-enabled: true
    base-url: http://zipkin-server:9411/
    #base-url: http://localhost:9411/
    #base-url: http://zipkin-server/
  sleuth:
    sampler:
      probability: 1.0

card-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000
    
logging:
  level:
    br.com.microservices.customerservice.client.CardClient: DEBUG  
   
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
hystrix:
  command:
    CardClient#getTest():
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 5
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 5
      circuitBreaker:
        requestVolumeThreshold: 5