server:
  port: 8888

spring:
  config:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/filipehcds/config-repo
#          basedir: /home/filipe/ProjetoPessoal/remoteconfigserver
#          clone-on-start: true
          
management.endpoints.web.exposure.include: '*'