server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/filipehcds/config-repo.git
  security:
    user:
      name: configUser
      password: configPassword
      roles: SYSTEM