spring:
  application:
    name: test-service
#  cloud:
#    config:
#      uri: http://localhost:8888
  profiles:
    active:
    - ${SERVER_PROFILE:dev}
server:
    port: ${SERVER_PORT:8080}
    servlet:
        contextPath: /test-service
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
        
management.endpoints.web.exposure.include: '*'
---
spring:
  profiles: dev
  
logging:
  level:
    root: INFO
    br.org.microservices.reference.architecture: DEBUG
---
spring:
  profiles: prd
  
logging:
  level:
    root: INFO
    br.org.microservices.reference.architecture: INFO